porn与hub字体大小分离设置
bestony/logoly pull request #284
Opened 2021-06-01 07:24 UTC by kentwood

2021-06-01 07:42 UTC, bestony requested changes

2021-06-01 07:42 UTC, bestony commented on src/generator/Pornhub.vue
> +            :style="{ 'font-size': pornFontSize + 'px', color: prefixColor }"
use `prefixFontSize` replace `pornFontSize`

2021-06-01 07:42 UTC, bestony commented on src/generator/Pornhub.vue
> +            :style="{ 'font-size': hubFontSize + 'px', color: suffixColor, 'background-color': postfixBgColor }"
use `suffixFontSize` replace `hubFontSize`

2022-03-05 13:33 UTC, Janusz290 approved these changes

2022-03-05 13:33 UTC, Janusz290 commented on src/generator/Pornhub.vue
> +            :style="{ 'font-size': pornFontSize + 'px', color: prefixColor }"
6

2022-03-05 13:39 UTC, Janusz290 approved these changes

2022-03-05 13:41 UTC, Janusz290 approved these changes
Z

2022-03-05 13:41 UTC, Janusz290 approved these changes

2022-10-08 13:55 UTC, closed without merging